package org.ton.intellij.tolk.codeInsight

import org.ton.intellij.tolk.ide.configurable.tolkSettings

class TolkCodeInsightTest : TolkCodeInsightBaseTest() {
    override fun getTestDataPath(): String = "${super.testDataPath}/tests"

    override fun setUp() {
        super.setUp()
        val file = myFixture.copyDirectoryToProject("../tolk-stdlib", "tolk-stdlib")
        project.tolkSettings.explicitPathToStdlib = file.url
    }

    fun `test a-tests`() = doTest()
    fun `test allow-post-modification`() = doTest()
    fun `test annotations-tests`() = doTest()
    fun `test asm-arg-order`() = doTest()
    fun `test assignment-tests`() = doTest()
    fun `test bit-operators`() = doTest()
    fun `test bytesN-tests`() = doTest()
    fun `test calls-tests`() = doTest()
    fun `test cells-slices`() = doTest()
    fun `test codegen-check-demo`() = doTest()
    fun `test comments`() = doTest()
    fun `test comments-tests`() = doTest()
    fun `test constants-tests`() = doTest()
    fun `test dicts-demo`() = doTest()
    fun `test generics-1`() = doTest()
    fun `test generics-2`() = doTest()
    fun `test generics-3`() = doTest()
    fun `test generics-4`() = doTest()
    fun `test if-else-tests`() = doTest()
    fun `test indexed-access`() = doTest()
    fun `test inference-tests`() = doTest()
    fun `test inline-tests`() = doTest()
    fun `test intN-tests`() = doTest()
    fun `test logical-operators`() = doTest()
    fun `test match-by-expr-tests`() = doTest()
    fun `test meaningful-1`() = doTest()
    fun `test methods-tests`() = doTest()
    fun `test mutate-methods`() = doTest()
    fun `test never-type-tests`() = doTest()
    fun `test no-spaces`() = doTest()
    fun `test null-keyword`() = doTest()
    fun `test nullable-tensors`() = doTest()
    fun `test nullable-types`() = doTest()
    fun `test numbers-tests`() = doTest()
    fun `test op-priority`() = doTest()
    fun `test pack-unpack-1`() = doTest()
    fun `test pack-unpack-2`() = doTest()
    fun `test pack-unpack-3`() = doTest()
    fun `test pack-unpack-4`() = doTest()
    fun `test pack-unpack-5`() = doTest()
    fun `test pack-unpack-6`() = doTest()
    fun `test parse-address`() = doTest()
    fun `test pure-functions`() = doTest()
    fun `test remove-unused-functions`() = doTest()
    fun `test self-keyword`() = doTest()
    fun `test smart-cast-tests`() = doTest()
    fun `test some-tests-1`() = doTest()
    fun `test some-tests-2`() = doTest()
    fun `test some-tests-3`() = doTest()
    fun `test special-fun-names`() = doTest()
    fun `test strings-tests`() = doTest()
    fun `test struct-tests`() = doTest()
    fun `test test-math`() = doTest()
    fun `test try-catch-tests`() = doTest()
    fun `test type-aliases-tests`() = doTest()
    fun `test unbalanced-ret`() = doTest()
    fun `test unbalanced-ret-loops`() = doTest()
    fun `test union-types-tests`() = doTest()
    fun `test unreachable-5`() = doTest()
    fun `test use-before-declare`() = doTest()
    fun `test var-apply-tests`() = doTest()
}
