name: Build Plugin

on:
  workflow_dispatch:

jobs:
  generate-build-number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        id: buildnumber
        with:
          token: ${{ secrets.github_token }}
          prefix: rust
  build:
    needs: [ generate-build-number ]
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_buildNumber: ${{ needs.generate-build-number.outputs.build_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ":plugin:buildPlugin"
          gradle-home-cache-excludes: |
            caches/modules-2/files-2.1/com.jetbrains.intellij.idea

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: intellij-ton
          path: build/distributions/*.zip
